### ISSUE TITLE
About the camera intrinsic.

### ISSUE THREAD

**Issue by s1752729916** [TencentARC/InstantMesh#66]
hi,
thanks for you excellent work! 

I tried using another dataset for finetuning, but I found that the camera intrinsic used for dataset rendering was important for the performance. When I used the data rendered with fov=50 and used the result of zero123++ as inference input, I obtained the result shown below:
<img width="584" alt="截屏2024-05-05 14 28 30" src="https://github.com/TencentARC/InstantMesh/assets/42924289/0d139649-b818-4501-aaec-76b90f8db6aa">

 And if I finetuing on  the data rendered with fov=30, I get the following result:
<img width="583" alt="截屏2024-05-05 14 17 52" src="https://github.com/TencentARC/InstantMesh/assets/42924289/18cbd508-4641-4dcf-a582-2400d5624cef">

I guess the reason for this phenomenon may be due to zero123++ training on fov=30 data, but  you mentioned in another [issue](https://github.com/TencentARC/InstantMesh/issues/13#issuecomment-2061519912) that objaverse was rendered with fov=50, and the paper said that arbitrary multi-view generation models can be integrated. Can you help me explain this? Or can you confirm if you are using fov=50 or fov=30 for training data rendering?

**Comment by bluestyle97** [comment]
In fact, our full training dataset contains images rendered with both `fov=50` and `fov=30`. The `fov=50` images are the original training dataset of the reconstruction model while the `fov=30` images are initially rendered for fine-tuning Zero123++ v1.2. Since we migrate our model from Zero123++ v1.1 to v1.2, we must fine-tune the model on 'fov=30' images to make it work on the camera setting of v1.2.
